Repository naz-hage/ntools, pull requests merged in 2024-04, with the labels that each got.

#46 Create publish-docs.yml
  .github/workflows/dotnet-desktop.yml
  .github/workflows/publish-docs.yml
Labels: enhancement

#45 41 issue: Unable to complete the installation of NTools
  .github/workflows/publish-docs.yml
  .gitignore
  DevSetup/app-7-zip.json
  DevSetup/app-Dotnet_Runtime.json
  DevSetup/app-Git_for_Windows.json
  DevSetup/app-Ntools.json
  DevSetup/app-Powershell.json
  DevSetup/app-Sysinternals.json
  DevSetup/app-Visual_Studio_2022.json
  DevSetup/app-Visual_Studio_Build_Tools.json
  DevSetup/app-Visual_Studio_Code.json
  DevSetup/app-docker.json
  DevSetup/app-nuget.json
  DevSetup/app-python.json
  DevSetup/install.ps1
  DevSetup/install.psm1
  HISTORY.md
  Nbuild/BuildStarter.cs
  Nbuild/Cli.cs
  Nbuild/Nbuild - Backup.csproj
  Nbuild/Nbuild.csproj
  Nbuild/resources/app-MongoDB.json
  Nbuild/resources/file-version.ps1
  Nbuild/resources/install-ntools.ps1
  Nbuild/resources/ntools.json
  NbuildTests/BuildStarterTests.cs
  NbuildTests/CommandTests.cs
  README.md
  docs/additional-information.md
  docs/changelog.md
  docs/index.md
  docs/installation.md
  docs/ntools/nbackup.md
  docs/ntools/nbuild-targets.md
  docs/ntools/nbuild.md
  docs/ntools/nbuildtasks.md
  docs/ntools/ngit.md
  docs/usage.md
  install.bat
  install.ps1
  mkdocs.yml
  nbuild.targets
  ntools.sln
Labels: bug, Ready for review

#48 47-issue
  DevSetup/install.psm1
  DevSetup/setenv.ps1
  Nbuild/Cli.cs
  Nbuild/resources/common.targets
  NbuildTasks/Unzip.cs
  NbuildTasks/Zip.cs
  README.md
  docs/index.md
  docs/installation.md
  docs/ntools/devsetup.md
  docs/ntools/nbackup.md
  docs/ntools/nbuild-targets.md
  docs/ntools/nbuild.md
  docs/ntools/nbuildtasks.md
  docs/ntools/ngit.md
  docs/setup.md
  docs/usage.md
  mkdocs.yml
  nbuild.targets
  ntools.sln
Labels: Ready for review

#52 Fix typo and broken links in setup.md
  docs/setup.md
Labels: documentation, Ready for review

#51 49-issue - use mbuild.exe (64-bit)
  .github/workflows/dotnet-desktop.yml
  DevSetup/install-ntools.ps1
  Nbuild/BuildStarter.cs
  Nbuild/Nbuild - Backup.csproj
  NbuildTests/BuildStarterTests.cs
  ntools.sln
Labels: Ready for review

#54 Attempt to improve publish-docs.yml
  .github/workflows/dotnet-desktop.yml
  .github/workflows/publish-docs.yml
  ntools.sln
Labels: bug, enhancement, Ready for review
